namespace Game;

using System.Globalization;
using CsvHelper;
using CsvHelper.Configuration;

public static class Levels
{
    public static Board FromCsv(string basePath)
    {
        // basePath example: "data/levels/level1"
        var pathFloor = $"{basePath}_1.csv";
        var pathSurface = $"{basePath}_2.csv";

        var config = new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            NewLine = Environment.NewLine, // REVIEW Check if necessary
            HasHeaderRecord = false
        };
        // Open and create readers for both csv files
        using (var readerFloor = new StreamReader(pathFloor))
        using (var csvFloor = new CsvReader(readerFloor, config))
        using (var readerSurface = new StreamReader(pathSurface))
        using (var csvSurface = new CsvReader(readerSurface, config))
        {
            var recordsFloor = csvFloor.GetRecords<CsvRow>().ToList();
            var recordsSurface = csvSurface.GetRecords<CsvRow>().ToList();

            // Check both map layers have the same dimensions
            if (recordsFloor.Count != recordsSurface.Count ||
                recordsFloor[0].Values.Count != recordsSurface[0].Values.Count)
                throw new InvalidLevelFilesException("The CSV files for the level do not have the same dimensions");

            // NOTE Change dimensions here if the map ends up flipped
            var boardGrid = new GridCell[recordsFloor.Count, recordsFloor[0].Values.Count];
            for (int y = 0; y < recordsFloor.Count; y++)
            {
                var floorRow = recordsFloor[y].Values;
                var surfaceRow = recordsSurface[y].Values;
                for (int x = 0; x < floorRow.Count; x++)
                {
                    // NOTE Change here if the map ends up flipped
                    boardGrid[x, y] = new GridCell(
                        idToFloorElement[floorRow[x]],
                        idToSurfaceElement[surfaceRow[x]]
                    );
                }
            }
            return new Board(boardGrid);
        }
    }

    // TODO check actual IDs generated by tiled
    private static readonly Dictionary<int, FloorElement?> idToFloorElement = new()
    {
        [-1] = null,
        [0] = FloorElement.Floor,
        [1] = FloorElement.Target,
        [2] = FloorElement.PlayerGoal
    };
    private static readonly Dictionary<int, SurfaceElement?> idToSurfaceElement = new()
    {
        [-1] = null,
        [0] = SurfaceElement.Wall,
        [1] = SurfaceElement.Box,
        [2] = SurfaceElement.Player
    };

    private class CsvRow
    {
        public List<int> Values { get; set; } = new List<int>();
    }
}

public class InvalidLevelFilesException : Exception
{
    public InvalidLevelFilesException(string msg) : base(msg) { }
}
